spring:
  config:
    activate:
      on-profile: prod

feign:
  client:
    url: gateway:8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:
        http://${EUREKA_ID}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true